-- this file wil calculate orders 

CREATE VIEW ORDERS 
AS  
SELECT CUSTOMNER_NAME, COUNT(ORDER_NO) AS NO_OF_ORDER  
FROM CUSTOMER 
INNER JOIIN SUPPLIER 
	ON C.CUSTOMER_ID.S.CUSTOMER_ID 
GROUP BY ALL ;


